# Generated by Django 4.1.5 on 2023-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("ciudad", models.CharField(max_length=100)),
                ("comuna_o_corregimiento", models.CharField(max_length=100)),
                (
                    "tema_de_interes",
                    models.CharField(
                        choices=[
                            ("artistico", "Artístico"),
                            ("donaciones", "Donaciones"),
                            ("sede_comunal", "Sede Comunal"),
                            ("transporte", "Transporte"),
                            ("voluntariado_diverso", "Voluntariado Diverso"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "medio_de_transporte",
                    models.CharField(
                        choices=[
                            ("moto", "Moto"),
                            ("carro", "Carro"),
                            ("bicicleta", "Bicicleta"),
                            ("a_pie", "A pie"),
                            ("transporte_publico", "Transporte público"),
                        ],
                        max_length=50,
                    ),
                ),
                ("apoyar_como_testigo_electoral", models.BooleanField()),
            ],
        ),
    ]
